#!/bin/bash
    clear
    figlet "NAOKI" | lolcat
    echo -e "\\033[46;1;37m              ★ NAOKI CHECKER MENU / NAOKI Checker မီနူး ★               \\033[0m"
    echo -e "\033[01;31m\033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 01 •\033[1;34m]\033[1;37m ➤  \033[1;33mINSTALL NAOKI CHECKER Conecta4G / NAOKI Checker Conecta4G တပ်ဆင်ရန် \033[0m"
	echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 02 •\033[1;34m]\033[1;37m ➤  \033[1;33mINSTALL NAOKI CHECKER DTunnel VPN / NAOKI Checker DTunnel VPN တပ်ဆင်ရန်\033[0m"
	echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 03 •\033[1;34m]\033[1;37m ➤  \033[1;33mINSTALL NAOKI CHECKER GL Tunnel VPN / NAOKI Checker GL Tunnel VPN တပ်ဆင်ရန် ⚠️\033[0m"
	echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 04 •\033[1;34m]\033[1;37m ➤  \033[1;33mINSTALL NAOKI CHECKER AnyVPN MOD / NAOKI Checker AnyVPN MOD တပ်ဆင်ရန်\033[0m"
    echo -e "\033[01;31m\033[1;31m\033[1;34m[\033[1;37m 00 •\033[1;34m]\033[1;37m ➤  \033[1;33mBACK / ပြန်သွားရန်  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
    echo -e "\033[01;31m\033[0m"
    echo -e "\033[0;36m░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░░★░\033[0m"
			tput civis
			echo -ne "\033[1;31m➤ \033[1;32mCHOOSE AN OPTION / ရွေးချယ်မှုကို ထည့်ပါ\033[1;33m\033[1;31m\033[1;37m : ";
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
			initcheck
			;;
			2 | 02)
            bash <(curl -sL https://raw.githubusercontent.com/ScottBrabo/DTunnel/main/MenuDT.sh)
            ;;
            3 | 03)
            bash <(curl -sL https://raw.githubusercontent.com/ScottBrabo/CheckUser/master/install.sh)
            ;;
            4 | 04)
            bash <(wget -qO- https://raw.githubusercontent.com/ScottBrabo/DTunnel/main/AnyChk)
            ;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mINVALID OPTION / မမှန်ကန်သော ရွေးချယ်မှု\033[0m"
			esac
			sleep 2
