#!/bin/bash
clear
#--------------------------
# SCRIPR SSH-PLUS
# CANAL TELEGRAM: @NAOKI_SSH
#--------------------------

# - Cores
RED='\033[1;31m'
YELLOW='\033[1;33m'
SCOLOR='\033[0m'

# - Verifica Execucao Como Root
[[ "$EUID" -ne 0 ]] && {
    echo -e "{RED}[x] YOU MUST RUN AS ROOT USER! / သင်သည် root user အဖြစ် လုပ်ဆောင်ရပါသည်!{SCOLOR}"
    exit 1
}

# - Verifica Arquitetura Compativel
case "$(uname -m)" in
    'amd64' | 'x86_64')
        arch='64'
        ;;
    'aarch64' | 'armv8')
        arch='arm64'
        ;;
    *)
        echo -e "${RED}[x] INCOMPATIBLE ARCHITECTURE / မကိုက်ညီသော Architecture !${SCOLOR}"
        exit 1
        ;;
esac

# - Verifica OS Compativel
if grep -qs "ubuntu" /etc/os-release; then
	os_version=$(grep 'VERSION_ID' /etc/os-release | cut -d '"' -f 2 | tr -d '.')
    [[ "$os_version" -lt 1804 ]] && {
        echo -e "${RED}[x] INCOMPATIBLE UBUNTU VERSION / မကိုက်ညီသော Ubuntu version !\n${YELLOW}[!] REQUIRES UBUNTU 18.04 OR NEWER / Ubuntu 18.04 သို့မဟုတ် အသစ် လိုအပ်သည် !${SCOLOR}"
        exit 1
    }
elif [[ -e /etc/debian_version ]]; then
	os_version=$(grep -oE '[0-9]+' /etc/debian_version | head -1)
    [[ "$os_version" -lt 9 ]] && {
        echo -e "${RED}[x] INCOMPATIBLE DEBIAN VERSION / မကိုက်ညီသော Debian version !\n${YELLOW}[!] REQUIRES DEBIAN 9 OR NEWER / Debian 9 သို့မဟုတ် အသစ် လိုအပ်သည် !${SCOLOR}"
        exit 1
    }
else
    echo -e "${RED}[x] INCOMPATIBLE OS / မကိုက်ညီသော OS !\n${YELLOW}[!] REQUIRES A DEBIAN/UBUNTU-BASED DISTRIBUTION / Debian/Ubuntu အခြေပြု OS လိုအပ်သည် !${SCOLOR}"
    exit 1
fi

# - Atualiza Lista/Pacotes/Sistema
dpkg --configure -a
apt update -y && apt upgrade -y
apt install unzip python3 -y

# - Desabilita ipv6
sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -p
echo 'net.ipv6.conf.all.disable_ipv6 = 1' > /etc/sysctl.d/70-disable-ipv6.conf
sysctl -p -f /etc/sysctl.d/70-disable-ipv6.conf

# - Execute installer
NAOKI_RELEASE="20260814-package-fix"
[[ -e Plus ]] && rm Plus
wget -O Plus "https://github.com/NaokiKun/NAOKI-SSH/raw/refs/heads/main/script/${arch}/Plus?release=${NAOKI_RELEASE}" && chmod 755 Plus && ./Plus
